name: Alpha CI

on:
  push:
    branches: [ master ]

concurrency:
  group: alpha-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      variant: Alpha
      detektTask: detektDebug
      appDistribution: true
      uploadOutputs: true
