name: Beta CI

on:
  push:
    branches: [ beta ]

concurrency:
  group: beta-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      variant: Beta
      detektTask: detektBeta
      appDistribution: true
      playStore: true
      uploadOutputs: true
