name: Release CI

on:
  push:
    branches: [ release ]

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      variant: Release
      detektTask: detektRelease
      appDistribution: true
      playStore: true
      incrementVersionCode: true
      uploadOutputs: true
